spring:
  application:
    name: java-api

  datasource:
    url: jdbc:postgresql://localhost:5433/user_management_db # Port 5433 olarak ayarlı!
    username: admin
    password: password123
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # otomatik olarak tablo oluşturma/güncelleme
    show-sql: true